coleslaw-org/coleslaw

docs/hacking.md
In order to better guide the prospect coleslaw contributor through the process. I wanted to keep it simple so I omitted the rebasing commits for when the PR has feedback.
Let me know what you think is missing or if a step is unclear.
Similar documents which could be used to expand the section are [Sly's contributing section](https://github.com/capitaomorte/sly/blob/master/CONTRIBUTING.md) and [SBCL's patch submission guide](https://github.com/sbcl/sbcl/blob/master/HACKING)
=> Add a contributing section to the hacking document

src/coleslaw.lisp
Coleslaw is able to write the blog content to xhtml file as well, using the
configuration setting :page-ext. But it did ignore the file extension when
creating the index page link responsible for the default landing page. With this
fix the file extension gets honored. E.g. when "xhtml" is configured, coleslaw
will generate a link from "index.xhtml" to "1.xhtml".
=> Supporting other file extensions for the index page as well.

src/config.lisp, src/packages.lisp
It's useful to have the ability to define plug-ins in the user repo, because some of them are inherently site-specific. Ie. I use a plug-in to change the way how 3bmd renders images:
```
```
is rendered as:
```
"<div class=\"img-wrapper\">"
"  <div class=\"img\">"
"    <img src=\"~a\" ~@[alt=\"~a\"~]/>"
"    <div class=\"img-caption\">~@[~a~]</div>"
"  </div>"
"</div>"
```
instead of the default:
```
"<img src=\"~a\" ~@[alt=\"~a\"~] ~@[title=\"~a\"~]/>
```
You can also use user plug-ing to tweak various things that are tweakable only in lisp.
=> Allow plug-ins to be defined in the user repo

plugins/static-pages.lisp
`format' in class `page' defaults to markdown to ensure backward
compatibility.
=> plugin: static-pages: allow specifying format

themes/hyde/base.tmpl, themes/readable/base.tmpl
This allows us providing not fully qualified url but to attach it to our
domain. This is helpful for static-pages when we navigate from inside a
post (which is nested deeper, like www.turtleware.eu/posts/xxx.html).
=> themes: add relative tag support for sitenav url

themes/hyde/base.tmpl, themes/hyde/css/style.css
Issue #104 
Firefox mobile did not even attempt to render the site as mobile and you would have to zoom in to read anything. Fixed with meta tag in first commit.
Afterwards, some CSS to try to:
- clean up the margin
- justify the font of the main body
-  default images to center of page, full width
- fix footnote
[Some images of before/after.](https://imgur.com/a/cIugB) They kinda got jumbled around, the ones with 3 tabs open are before shots.
Tested on Firefox and Chrome mobile on a Motorola E and Chrome/Firefox devtools. Changes should affect phones up until about an iPhone 6 Plus. 
Wasn't sure how far to go with some of the stuff like image tag css, and I am by no means a CSS expert, so feel free to give opinions/suggestions.
=>  #104 - mobile CSS updates for hyde

coleslaw-conf.asd, coleslaw-test.asd, coleslaw.asd, src/coleslaw-conf.lisp, tests/tests.lisp
Ideally the package coleslaw would only have symbols that refer to
configuration variables. However to ease setting *BASEDIR* to the right
value using UIOP:SYMBOL-CALL we provide a setter, SET-BASEDIR. Btw, the previous code had an implementation defined use list.
- Split each ASDF system into its own file
- All system definitions are made in the ASDF-USER package, as
recommended by ASDF.
Fixes #110
=> Move coleslaw-conf to its own ASDF system

tests/tests.lisp
Check for the presence of plugins and themes sub-directories. This is to
ensure that COLESLAW-CONF:*BASEDIR* is not bound the directory of the
FASL cache.
=> Improve COLESLAW-CONF:*BASEDIR* tests

.gitignore
CCL has different prefixes for different platforms[0].
[0]: http://ccl.clozure.com/manual/chapter3.1.html
=> Ignore Linux CCL FASL files

docs/plugin-use.md, plugins/3bmd-youtube.lisp
This plugin allows users to use a shorthand syntax to embed youtube
videos in markdown
Closes #124
=> Add 3bmd youtube plugin

src/indexes.lisp
Month parsing was removed in 2ee26090, don't think it was intended though.
=> Get the month from content-date, if exists, instead of whole date.

docs/plugin-use.md, plugins/mathjax.lisp
MathJax's CDN is [shutting down](https://www.mathjax.org/cdn-shutting-down/) I've changed to cdnjs as suggested in the article. Note that:
* Version number must be changed manually (there's no latest anymore.)
* I've changed from HTTP to HTTPS which is I think a safer default.
=> Mathjax cdn update

README.md
common-lisp.net has graciously made a mailing list for coleslaw (at my request, by snail mail). I'd be happy to hand out permissions to the current maintainers of Coleslaw. Currently it is just me; hopefully this is okay.
coleslaw@common-lisp.net
https://mailman.common-lisp.net/listinfo/coleslaw
=> Add mailing list from common-lisp.net

docs/plugin-use.md, plugins/markless.lisp
This plugin allows writing articles using the [Markless](https://shirakumo.github.io/markless) language.
=> Markless plugin through cl-markless-plump

cli/cli.lisp, docs/plugin-use.md, plugins/rsync.lisp, src/coleslaw.lisp, src/config.lisp
=> Removed the default deploy method and added RSYNC plugin

plugins/incremental.lisp, src/documents.lisp, src/util.lisp
I want to be able to add differently rendered/themes post 'sub-types' to my blog ( linkblog entries, photo galleries, journal entries etc. ).
To this end, I'm experimenting with a plugin that allows me to subclass existing document types, to add additional properties/slots that can be handled conditionally.
I ran into a small snag, in as much as the current implementation of find-all is too greedy wrt matching on type of document.
The existing implementation of find-all implementation returns false positives for subclasses
I added a parameter of a predicate to implement matching, with a default value that preserves original behaviour
I then added an exact class matcher to purge-all invocation of find-all to stop it purging subclasses
=> find-all matching adjusted

docs/plugin-use.md, plugins/git-versioned.lisp, src/util.lisp
Fully automated git versioning upon static content deployment. This is a drop-in
replacement of the `versioned` plugin, which uses symlink cycling, and is
superior to it since it is just a git repo. This is different from a gh-pages
repo, in that it only assumes the free program `git` is available, and not the
proprietary platform github.com
It is also possible to store the staging directory inside of the source
directory, although this may result in slow commit times as git tries to deal
with version controlling the whole site.
`(git-versioned "~/path/to/src/dir" 'stage)`
`git-versioned` needs to know where the source is so it can run `git` commands
from that directory. Here all the commands implemented:
- `stage` runs `git stage -A`
- `commit` runs `git commit -m "Automatic commit."`
- …
=> Git versioned plugin

docs/plugin-use.md, plugins/gtag.lisp
The new setup for google analytics recommends the following code snippet: 
Thus, the new plugin uses that as the code to be injected. It is modeled after the current analytics plugin.
=> Update google analytics integration: create gtag plugin

cli/cli.lisp, plugins/sitemap.lisp
In this PR I fix the existing sitemap plugin. 
This fixes these two PRs:
- https://github.com/coleslaw-org/coleslaw/issues/142
- https://github.com/coleslaw-org/coleslaw/issues/84
As mentioned in this comment by @PuercoPop https://github.com/coleslaw-org/coleslaw/issues/142#issuecomment-335061002, the sitemap class is subclassing index. Additionally, the entry for the sitemap has to be added to routing in the config for the plugin to work.
https://user-images.githubusercontent.com/28762146/133953586-08b6464b-afff-4df2-a155-0c7a8aadb5e0.mov
=> make sitemap subclass index, add to routing

docs/config.md, src/coleslaw.lisp, src/config.lisp, src/documents.lisp
Allow for fine-grained control of URL generation including file extensions and
name functions.
_page extensions_
I wanted posts to have no extension (via :page-ext), so I had to modify the
code to allow for :page-ext "" to work, and without inserting a dot at the end
of my files.
_index extensions_
Doing the edits to page-ext broke my index symlink, so I had to add
:index-ext to the config.
_name-fn, calling a function on the title_
The default way for coleslaw to generate the post URL is to just use the title,
inserting dashes for spaces. I wanted lowercase URLs though, so I made
:name-fn in the config to define a function like :name-fn string-downcase
for making the URLs. The default is identity, so it won't change your old
URLs.
=> Control of URL generation -- extensions and name-fn

examples/example.post-receive
coleslaw:main got changed to take the old revision as a &key argument, but the example code was not updated.
=> Add :oldrev key to call to coleslaw:main
